(in-package :stack-dsl)

(defclass stack-dsl-parser (pasm:parser)
  ((savedSymbol :accessor savedSymbol)
   (or-list :accessor or-list)
   (enum-list :accessor enum-list)
   (field-list :accessor field-list)
   (existence-list :accessor existence-list)
   (target-package :accessor target-package :initform "STACK-DSL")))

(defmethod initially ((self stack-dsl-parser) token-list)
  (setf (savedSymbol self) nil)
  (setf (or-list self) nil)
  (setf (enum-list self) nil)
  (setf (field-list self) nil)
  (setf (existence-list self) nil)
  (call-next-method))
